# Generated by Django 3.1.4 on 2020-12-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
