# Generated by Django 3.1.4 on 2020-12-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='creator',
            field=models.CharField(default='shop', max_length=200),
            preserve_default=False,
        ),
    ]
