version: '3.7'

services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    command: python SanyaShop/manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: "redis"
    ports:
     - "6379:6379"
